sonar.projectKey=ramis-front
sonar.projectName=ramis-front
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test

sonar.sourceEncoding=UTF-8

sonar.flutter.enabled=true

sonar.exclusions=**/*.g.dart,**/build/**
