# Identificadores únicos del proyecto en el servidor de SonarQube
sonar.projectKey=ramistoolx-front
sonar.projectName=Ramis Tool X - Frontend Movil
sonar.branch.name=master
sonar.projectVersion=1.0

# Rutas de las carpetas que SonarQube va a escanear
sonar.sources=lib
sonar.tests=test

# Lenguaje principal a auditar
sonar.language=dart

# Excluir archivos auto-generados por Flutter que no necesitan auditoría
sonar.exclusions=**/*.g.dart, **/*.freezed.dart
sonar.login=squ_dbf5091853de92297c71f5865a47940b1bccf856