pipeline {
agent any

```
tools {
    sonarQubeScanner 'sonar-scanner'
}

stages {

    stage('Clonar Repositorio') {
        steps {
            echo 'Descargando el código desde GitHub...'
            git branch: 'master',
                url: 'https://github.com/JaleaReal-1/ramis-front.git'
        }
    }

    stage('Instalar Dependencias') {
        steps {
            echo 'Descargando paquetes Flutter...'
            sh '/opt/flutter/bin/flutter pub get'
        }
    }

    stage('Pruebas Unitarias') {
        steps {
            echo 'Ejecutando pruebas...'
            sh '/opt/flutter/bin/flutter test'
        }
    }

    stage('Analisis SonarQube') {
        steps {
            script {
                def scannerHome = tool 'sonar-scanner'

                withSonarQubeEnv('SonarServer') {
                    sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=ramis-front \
                        -Dsonar.projectName=ramis-front \
                        -Dsonar.sources=lib \
                        -Dsonar.tests=test
                    """
                }
            }
        }
    }

    stage('Compilar APK') {
        steps {
            echo 'Generando APK Release...'
            sh '/opt/flutter/bin/flutter build apk --release'
        }
    }

}

post {

    success {
        echo 'Pipeline completado correctamente.'

        archiveArtifacts(
            artifacts: 'build/app/outputs/flutter-apk/app-release.apk',
            fingerprint: true
        )
    }

    failure {
        echo 'El pipeline fallo.'
    }

    always {
        cleanWs()
    }
}
```

}
